env:
  browser: true
  es2020: true
  jquery: true
globals:
  FB: readonly
plugins:
  - babel
  - react
extends:
  - standard
  - prettier
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
rules:
  # TODO: Migrate to camelcase.
  # snake_case API params and properties makes this a tangled process.
  camelcase: off
  'no-console': off
  'no-use-before-define': off
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
settings:
  react:
    version: detect
