export default {
  space: [0, 4, 8, 16, 24, 32, 42, 56, 72, 96, 128, 256, 512],
  fonts: {
    heading: "Space Grotesk, monospace",
    body: "Inter, sans-serif",
    survey: "Manrope, sans-serif",
    monospace: "Space Grotesk, monospace",
  },
  fontSizes: [12, 14, 16, 20, 24, 36, 48, 64, 96],
  fontWeights: {
    body: 400,
    survey: 400,
    heading: 700,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  colors: {
    text: "#60656F",
    background: "#FFF",
    primary: "#62a6ef",
    primaryLight: "#62a6ef",
    secondary: "#F6F7F8",
    mediumGray: "#8f8f8f",
    lightGray: "#afafaf",
    lighterGray: "#eee",
    bgGray: "#fcfcfc",
    primaryActive: "#5398e2",
    secondaryActive: "#e0e4e7",
    mediumGrayActive: "#63676e",
    lightGrayActive: "#9f9f9f",
    mediumRed: "#e26666",
    mediumRedActive: "#d32d28",
    mediumGreen: "#5fa240",
    mediumGreenActive: "#448b24",
  },
  links: {
    text: {
      fontWeight: "600",
      color: "primary",
      "&:visited": {
        color: "primary",
      },
      "&:active": {
        color: "primary",
      },
      "&:hover": {
        color: "primary",
        textDecoration: "underline",
      },
      textDecoration: "none",
      cursor: "pointer",
    },
    button: {
      px: [3],
      py: [2],
      borderRadius: "4px",
      backgroundColor: "primary",
      textDecoration: "none",
      color: "background",
      "&:hover": {
        bg: "primaryActive",
      },
      bg: "primary",
      fontFamily: "monospace",
      cursor: "pointer",
    },
    nav: {
      fontFamily: "monospace",
      color: "inherit",
      "&.active": {
        color: "primary",
      },
      "&:hover": {
        color: "primary",
        borderBottom: "1.5px solid",
        borderBottomColor: "primary",
      },
      textDecoration: "none",
      fontSize: [2],
      fontWeight: "bold",
      cursor: "pointer",
      borderBottom: "1.5px solid",
      borderBottomColor: "background",
    },
    activeNav: {
      fontFamily: "monospace",
      color: "inherit",
      "&.active": {
        color: "primary",
      },
      "&:hover": {
        color: "primary",
        borderBottomColor: "primary",
      },
      textDecoration: "none",
      mr: [4],
      fontSize: [2],
      fontWeight: "bold",
      cursor: "pointer",
      borderBottom: "1.5px solid",
      borderBottomColor: "mediumGray",
    },
  },
  buttons: {
    primary: {
      color: "background",
      bg: "primary",
      "&:hover": {
        bg: "primaryActive",
      },
      fontFamily: "monospace",
      cursor: "pointer",
    },
    secondary: {
      color: "background",
      bg: "lightGray",
      "&:hover": {
        bg: "lightGrayActive",
      },
      fontFamily: "monospace",
      cursor: "pointer",
    },
    outline: {
      color: "primary",
      bg: "background",
      fontFamily: "monospace",
      cursor: "pointer",
      border: "1px solid",
      borderColor: "primary",
      "&:hover": {
        color: "primaryActive",
        borderColor: "primaryActive",
      },
    },
    outlineSecondary: {
      color: "lightGray",
      bg: "background",
      fontFamily: "monospace",
      cursor: "pointer",
      border: "1px solid",
      borderColor: "lightGray",
      "&:hover": {
        color: "lightGrayActive",
        borderColor: "lightGrayActive",
      },
    },
    outlineRed: {
      color: "mediumRed",
      bg: "background",
      fontFamily: "monospace",
      cursor: "pointer",
      border: "1px solid",
      borderColor: "mediumGray",
      "&:hover": {
        color: "mediumRedActive",
        borderColor: "mediumRedActive",
      },
    },
    outlineGreen: {
      color: "mediumGreen",
      bg: "background",
      fontFamily: "monospace",
      cursor: "pointer",
      border: "1px solid",
      borderColor: "mediumGray",
      "&:hover": {
        color: "mediumGreenActive",
        borderColor: "mediumGreenActive",
      },
    },
    outlineLightGray: {
      color: "lightGray",
      bg: "background",
      fontFamily: "monospace",
      cursor: "pointer",
      border: "1px solid",
      borderColor: "lightGray",
      "&:hover": {
        color: "lightGrayActive",
        borderColor: "lightGrayActive",
      },
    },
    outlineGray: {
      color: "mediumGray",
      bg: "background",
      fontFamily: "monospace",
      cursor: "pointer",
      border: "1px solid",
      borderColor: "mediumGray",
      "&:hover": {
        color: "mediumGrayActive",
        borderColor: "mediumGrayActive",
      },
    },
  },
  cards: {
    primary: {
      backgroundColor: "background",
      color: "mediumGray",
      padding: 3,
      borderRadius: 4,
      boxShadow: "0 0 8px rgba(0, 0, 0, 0.125)",
    },
  },
  styles: {
    root: {
      fontFamily: "body",
      lineHeight: "body",
      fontWeight: "body",
    },
    a: {
      color: "primary",
      "&:visited": {
        color: "primary",
      },
      "&:active": {
        color: "primary",
      },
      "&:hover": {
        color: "primary",
        borderBottom: "solid",
        borderWidth: 1.5,
        borderColor: "primary",
      },
      textDecoration: "none",
      cursor: "pointer",
      borderBottom: "solid",
      borderWidth: 2,
      borderColor: "background",
    },
  },
}
